# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ownershit < Formula
  desc "Manage the ownership of your repositories."
  homepage ""
  version "0.5.3"

  on_macos do
    url "https://github.com/klauern/ownershit/releases/download/v0.5.3/ownershit_0.5.3_darwin_amd64.tar.gz"
    sha256 "099da6c55dec07827f2467905856b3e1df7ed4e72a84c1b141d0c78e9e913065"

    def install
      bin.install "ownershit"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ownershit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/klauern/ownershit/releases/download/v0.5.3/ownershit_0.5.3_linux_armv6.tar.gz"
      sha256 "bdec6a6b918283ed73671b43cdfc9326796d6bcc36037db4dfbb8dcc7ccceec6"

      def install
        bin.install "ownershit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/klauern/ownershit/releases/download/v0.5.3/ownershit_0.5.3_linux_amd64.tar.gz"
      sha256 "9e612f0d02928505fc611110acb9db8c05d035112f82a382659573e7ff2fd343"

      def install
        bin.install "ownershit"
      end
    end
  end
end
